META_QUESTION_PHRASES = {
  "first_question": [
    "what was my first question",
    "tell me the first thing i asked",
    "can you recall my first question",
    "what did i ask at the beginning",
    "initial question i asked",
    "first query",
    "start of our conversation",
    "beginning question",
    "what did i ask first",
    "my starting question",
    "what was the opening question",
    "tell me the initial thing I asked",
    "how did this chat start",
    "recall my first query",
    "which question started it all",
    "what did I begin with",
    "what's the first message I sent",
    "first thing I said",
    "beginning of the conversation",
    "initial thing I asked"
  ],
  "last_question": [
    "what was the last question i asked",
    "most recent question",
    "tell me my previous question",
    "previous query",
    "last query i made",
    "what did i ask just now",
    "recent question",
    "the last thing i asked",
    "final question",
    "latest question",
    "what did I just ask",
    "my latest query",
    "what was my most recent question",
    "tell me the last thing I said",
    "recall my last input",
    "what was my closing question",
    "most up-to-date question",
    "last thing I typed",
    "final thing I asked",
    "wrap-up question"
  ],
  "count": [
    "how many questions did i ask",
    "total number of questions",
    "number of questions i asked",
    "how many queries so far",
    "count my questions",
    "total queries",
    "how many times have i asked",
    "total interactions",
    "give me the count of questions",
    "question count",
    "how many questions have we gone through",
    "can you count my queries",
    "how many entries have I made",
    "question total",
    "total times I asked something",
    "query count",
    "how many messages did I send",
    "how often did I ask a question",
    "give me the total question number",
    "complete count of my questions"
  ],
  "list_questions": [
    "list all my questions",
    "show me all the questions i asked",
    "what are all the questions i asked",
    "questions i asked so far",
    "print my questions",
    "recap my questions",
    "can you list what i asked",
    "what were all my queries",
    "show history of my questions",
    "previous questions list",
    "can you list all my previous questions",
    "what questions have I asked till now",
    "recall all my queries",
    "all my past questions",
    "full list of questions I asked",
    "complete question history",
    "enumerate my questions",
    "show me every question I asked",
    "past queries log",
    "list of all my inquiries"
  ],
  "list_answers": [
    "list all the answers",
    "show my answers",
    "what were your responses",
    "give me all your replies",
    "print all answers",
    "answer history",
    "can you show all your responses",
    "summarize all the answers you gave",
    "recap your answers",
    "list responses",
    "show me your full set of answers",
    "all the replies you gave",
    "display the answers you provided",
    "complete list of responses",
    "list of replies",
    "your response log",
    "what were all your answers",
    "recap your past responses",
    "response summary",
    "what have you said so far"
  ],
  "summary": [
    "summarize our chat",
    "give me a summary of my questions",
    "brief summary of this chat",
    "summary of conversation",
    "can you summarize",
    "quick overview of our discussion",
    "short recap of the conversation",
    "chat recap",
    "tell me what we talked about",
    "give me the gist",
    "give me a recap of our interaction",
    "summarize what we discussed",
    "chat session summary",
    "overview of our messages",
    "what have we covered",
    "quick chat breakdown",
    "brief overview of this session",
    "highlight what we talked about",
    "conversation wrap-up",
    "key points of our chat"
  ],
  "nth_question": [
    "what was my second question",
    "tell me the third thing i asked",
    "what was my 4th question",
    "give me my question number 5",
    "what was question number 2",
    "what did i ask fourth",
    "my 6th question",
    "recall question number 3",
    "question number seven",
    "which question was number 8",
    "tell me what my 10th question was",
    "which question was number 11",
    "recall my 12th question",
    "what did I ask in question number 9",
    "show question number 13",
    "what was the 15th question",
    "give me the 14th query",
    "repeat question number 6",
    "show me my 3rd question",
    "display the fifth question I asked"
  ],
  "nth_answer": [
    "what was the answer to my second question",
    "give me the answer to question 3",
    "response to my 4th question",
    "what did you say to my 5th question",
    "answer number 6",
    "what was your reply to my 7th query",
    "answer to question 8",
    "response for question number 2",
    "what was said for my third question",
    "tell me the answer to my 9th question",
    "show me the answer to my 10th question",
    "what was your reply to my 12th question",
    "response to my 9th query",
    "recap your answer to question 11",
    "answer number 13 please",
    "what did you say to my 6th question",
    "give me your response to question 7",
    "remind me what you said for question 5",
    "repeat your answer to the 8th question",
    "what did you say to the 3rd one"
  ]
}
